### ISSUE TITLE
Add web page margins on left and right.

### ISSUE THREAD

**Issue by MyKoalaDev** [ikap22/350researchproject#1]
As a WEBSITE USER,
I want MARGINS ON EITHER SIDE OF THE WEB PAGE,
so that I CAN BROWSE ADS WHILE "READING" YOUR ARTICLES.
## Priority: Blocking release

assignees: tim

**Comment by timmy0402** [comment]
There will be subway suffer added on both margins at release.
Thanks for your generous feedback
